![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(my_array[::-2])

[9 7 5 3 1]


In [5]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(my_array[2::-1])

[2 1 0]


In [10]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [11]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [12]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [14]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [16]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [17]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [19]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [21]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [23]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [24]:
x == "Loro"

array([ True, False, False,  True, False])

In [25]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [26]:
print(np.where(x== "Loro")[0])

[0 3]


In [27]:
print(np.where(x == "Loro")[0])

[0 3]


In [28]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [29]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [30]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [31]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [32]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [38]:
ceros = np.array([0,0,0,0,0,0,0,0,0,0])
ceros[3] =1
print(ceros)
print(ceros.nbytes)

[0 0 0 1 0 0 0 0 0 0]
80


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [34]:
vector_1 = np.array([10,0])
vector_2 = np.array([49,0])
vector = vector_2-vector_1
print(vector)
print(vector[::-1])

[39  0]
[ 0 39]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [40]:
j =np.array[1,2,0,0,4,0]
np.where(j !=0)

TypeError: 'builtin_function_or_method' object is not subscriptable

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [35]:
print(np.random.randint(10, size = (10,10)))

[[3 6 8 3 3 6 5 6 9 4]
 [6 8 4 5 1 6 7 2 7 3]
 [7 7 3 9 7 8 5 3 4 7]
 [0 8 2 4 2 2 4 6 6 0]
 [8 0 0 6 5 4 0 9 2 2]
 [9 9 2 3 2 8 2 6 0 0]
 [1 7 3 9 3 2 4 5 4 4]
 [1 5 2 9 3 5 1 9 8 4]
 [7 0 5 9 8 4 8 0 9 9]
 [3 7 1 7 5 3 8 9 2 6]]


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [42]:
vector = np.random.randint(0,6,(5,5))
print(vector)
media = np.mean(vector)
print(media)

[[1 1 0 4 1]
 [1 4 1 1 0]
 [1 1 3 2 5]
 [1 2 2 0 4]
 [2 5 1 2 4]]
1.96


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [37]:
print(np.random.randint(10, size = (5,5)))

[[1 7 6 4 8]
 [3 8 1 9 3]
 [4 9 4 4 0]
 [9 7 8 6 4]
 [4 5 5 5 1]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [43]:
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])